apps/about/urls.py
# apps/about/urls.py

# Django modules
from django.urls import path

# Django locals
from apps.about.views import about_page

app_name = 'about'

urlpatterns = [
    path('', about_page, name='about_page'),
]

apps/contact/urls.py
# apps/contact/urls.py

# Django modules
from django.urls import path

# Django locals
from apps.contact.views import contact_page

app_name = 'contact'

urlpatterns = [
    path('', contact_page, name='contact_page'),
]

apps/dashboard/urls.py
# apps/dashboard/urls.py

# Django modules
from django.urls import path

# Django locals
from apps.dashboard.views import dashboard, news_list, news_add

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('news/list', news_list, name='news_list'),
    path('news/add', news_add, name='news_add'),
]

apps/main/urls.py
# apps/main/urls.py

# Django modules
from django.urls import path

# Django locals
from apps.main.views import home_page

app_name = 'main'

urlpatterns = [
    path('', home_page, name='home_page'),
]

config/urls.py
# config/urls.py

# Django modules
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    
    # Main app
    path('', include('apps.main.urls', namespace='main')),
    
    # About app
    path('about/', include('apps.about.urls', namespace='about')),
    
    # Contact app
    path('contact/', include('apps.contact.urls', namespace='contact')),
    
    # Admin app
    path('panel/', include('apps.dashboard.urls', namespace='dashboard')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/dashboard/models.py
from django.db import models

# Create your models here.

apps/news/models.py
# apps/news/models.py

# Django modules
from __future__ import unicode_literals
from django.db import models

# Django locals

# Create your models here.

class News(models.Model):

    title = models.CharField(max_length=150, blank=False)
    short_txt = models.TextField()
    body_txt = models.TextField()
    date = models.CharField(max_length=12)
    pic = models.TextField()
    writer = models.CharField(max_length=50)

    class Meta:
    	verbose_name = "News"
    	verbose_name_plural = "News"

    def __str__(self):
        return self.title
  

     

apps/about/views.py
# apps/about/views.py

# Django modules
from django.shortcuts import render

# Create your views here.

# Homepage view
def about_page(request):
	return render(request, 'about/about_page.html')

apps/contact/views.py
# apps/contact/views.py

# Django modules
from django.shortcuts import render

# Create your views here.

# Homepage view
def contact_page(request):
	return render(request, 'contact/contact_page.html')

apps/dashboard/views.py
# apps/dashboard/views.py

# Django modules
from django.shortcuts import render

# Django locals
from apps.news.models import News
# Create your views here.

# Homepage view
def dashboard(request):
	return render(request, 'dashboard/dashboard.html')


def news_list(request):
	news_lists = News.objects.all()
	print(news_lists)
	context = {
		'news_lists':news_lists
	}
	return render(request, 'dashboard/news_list.html', context)


def news_add(request):

	return render(request, 'dashboard/news_add.html')

apps/main/views.py
# apps/main/views.py

# Django modules
from django.shortcuts import render

# Django locals
from apps.news.models import News

# Create your views here.

# Homepage view
def home_page(request):
	news_lists = News.objects.all()
	context = {
		'news_lists':news_lists
	}
	return render(request, 'main/home_page.html', context)

templates/about/about_page.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{block.super}} About {% endblock title %}

{% block content %}

<!-- Breadcrumb -->
<div class="container">
	<div class="headline bg0 flex-wr-sb-c p-rl-20 p-tb-8">
		<div class="f2-s-1 p-r-30 m-tb-6">
			<a href="index.html" class="breadcrumb-item f1-s-3 cl9">
				Home 
			</a>

			<span class="breadcrumb-item f1-s-3 cl9">
				About Us
			</span>
		</div>

		<div class="pos-relative size-a-2 bo-1-rad-22 of-hidden bocl11 m-tb-6">
			<input class="f1-s-1 cl6 plh9 s-full p-l-25 p-r-45" type="text" name="search" placeholder="Search">
			<button class="flex-c-c size-a-1 ab-t-r fs-20 cl2 hov-cl10 trans-03">
				<i class="zmdi zmdi-search"></i>
			</button>
		</div>
	</div>
</div>

<!-- Page heading -->
<div class="container p-t-4 p-b-35">
	<h2 class="f1-l-1 cl2">
		About Us
	</h2>
</div>

<!-- Content -->
<section class="bg0 p-b-110">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-7 col-lg-8 p-b-30">
				<div class="p-r-10 p-r-0-sr991">
					<p class="f1-s-11 cl6 p-b-25">
						Curabitur volutpat bibendum molestie. Vestibulum ornare gravida semper. Aliquam a dui suscipit, fringilla metus id, maximus leo. Vivamus sapien arcu, mollis eu pharetra vitae, condimentum in orci. Integer eu sodales dolor. Maecenas elementum arcu eu convallis rhoncus. Donec tortor sapien, euismod a faucibus eget, porttitor quis libero. 
					</p>

					<p class="f1-s-11 cl6 p-b-25">
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet est vel orci luctus sollicitudin. Duis eleifend vestibulum justo, varius semper lacus condimentum dictum. Donec pulvinar a magna ut malesuada. In posuere felis diam, vel sodales metus accumsan in. Duis viverra dui eu pharetra pellentesque. Donec a eros leo. Quisque sed ligula vitae lorem efficitur faucibus. Praesent sit amet imperdiet ante. Nulla id tellus auctor, dictum libero a, malesuada nisi. Nulla in porta nibh, id vestibulum ipsum. Praesent dapibus tempus erat quis aliquet. Donec ac purus id sapien condimentum feugiat.
					</p>

					<p class="f1-s-11 cl6 p-b-25">
						Praesent vel mi bibendum, finibus leo ac, condimentum arcu. Pellentesque sem ex, tristique sit amet suscipit in, mattis imperdiet enim. Integer tempus justo nec velit fringilla, eget eleifend neque blandit. Sed tempor magna sed congue auctor. Mauris eu turpis eget tortor ultricies elementum. Phasellus vel placerat orci, a venenatis justo. Phasellus faucibus venenatis nisl vitae vestibulum. Praesent id nibh arcu. Vivamus sagittis accumsan felis, quis vulputate
					</p>
				</div>
			</div>
			
			<!-- sidebar_popular_posts -->
			{% include "shared/sidebar_popular_posts.html" %}
			<!-- sidebar_popular_posts -->
		</div>
	</div>
</section>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>MagNews | {% block title %}{% endblock title %}</title>
	<!-- head -->
	{% include "shared/head.html" %}
	<!-- head -->
</head>
<body class="animsition">
	
	<!-- Header -->
	<header>
		<!-- Header desktop -->
		<div class="container-menu-desktop">

			<!-- header_topbar -->
			{% include "shared/header_topbar.html" %}			
			<!-- header_topbar -->

			<!-- header_logo_mobile -->
			{% include "shared/header_logo_mobile.html" %}
			<!-- header_logo -->

			<!-- header_mobile_menu -->
			{% include "shared/header_mobile_menu.html" %}
			<!-- header_mobile_menu -->

			<!-- header_logo_desktop -->
			{% include "shared/header_logo_desktop.html" %}
			<!-- header_logo_desktop -->

			<!-- header_desktop_menu -->
			{% include "shared/header_desktop_menu.html" %}	
			<!-- header_desktop_menu -->
		</div>
	</header>

	{% block content %}
	{% endblock content %}
	
	<!-- Footer -->
	<footer>
		<div class="bg2 p-t-40 p-b-25">
			<div class="container">
				<div class="row">

					<!-- footer_info -->
					{% include "shared/footer_info.html" %}
					<!-- footer_info -->

					<!-- footer_popular_posts -->
					{% include "shared/footer_popular_posts.html" %}
					<!-- footer_popular_posts -->

					<!-- footer_categories -->
					{% include "shared/footer_categories.html" %}
					<!-- footer_categories -->
				</div>
			</div>
		</div>

		<!-- footer_copyright -->

		<!-- footer_copyright -->
	</footer>

	<!-- Back to top -->
	<div class="btn-back-to-top" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<span class="fas fa-angle-up"></span>
		</span>
	</div>

	<!-- Modal Video 01-->
	<div class="modal fade" id="modal-video-01" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog" role="document" data-dismiss="modal">
			<div class="close-mo-video-01 trans-0-4" data-dismiss="modal" aria-label="Close">&times;</div>

			<div class="wrap-video-mo-01">
				
			</div>
		</div>
	</div>

<!-- footer_scripts -->
{% include "shared/footer_scripts.html" %}
<!-- footer_scripts -->

</body>
</html>

templates/contact/contact_page.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{block.super}} Contact {% endblock title %}

{% block content %}

<!-- Breadcrumb -->
<div class="container">
	<div class="headline bg0 flex-wr-sb-c p-rl-20 p-tb-8">
		<div class="f2-s-1 p-r-30 m-tb-6">
			<a href="index.html" class="breadcrumb-item f1-s-3 cl9">
				Home 
			</a>

			<span class="breadcrumb-item f1-s-3 cl9">
				Contact Us
			</span>
		</div>

		<div class="pos-relative size-a-2 bo-1-rad-22 of-hidden bocl11 m-tb-6">
			<input class="f1-s-1 cl6 plh9 s-full p-l-25 p-r-45" type="text" name="search" placeholder="Search">
			<button class="flex-c-c size-a-1 ab-t-r fs-20 cl2 hov-cl10 trans-03">
				<i class="zmdi zmdi-search"></i>
			</button>
		</div>
	</div>
</div>

<!-- Page heading -->
<div class="container p-t-4 p-b-40">
	<h2 class="f1-l-1 cl2">
		Contact Us
	</h2>
</div>

<!-- Content -->
<section class="bg0 p-b-60">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-7 col-lg-8 p-b-80">
				<div class="p-r-10 p-r-0-sr991">
					<form>
						<input class="bo-1-rad-3 bocl13 size-a-19 f1-s-13 cl5 plh6 p-rl-18 m-b-20" type="text" name="name" placeholder="Name*">

						<input class="bo-1-rad-3 bocl13 size-a-19 f1-s-13 cl5 plh6 p-rl-18 m-b-20" type="text" name="email" placeholder="Email*">

						<input class="bo-1-rad-3 bocl13 size-a-19 f1-s-13 cl5 plh6 p-rl-18 m-b-20" type="text" name="website" placeholder="Website">

						<textarea class="bo-1-rad-3 bocl13 size-a-15 f1-s-13 cl5 plh6 p-rl-18 p-tb-14 m-b-20" name="msg" placeholder="Your Message"></textarea>

						<button class="size-a-20 bg2 borad-3 f1-s-12 cl0 hov-btn1 trans-03 p-rl-15 m-t-20">
							Send
						</button>
					</form>
				</div>
			</div>
			
			<!-- sidebar_popular_posts -->
			{% include "shared/sidebar_popular_posts.html" %}
			<!-- sidebar_popular_posts -->
		</div>
	</div>
</section>

{% endblock content %}

templates/dashboard/base.html
{% load static %}

<!DOCTYPE html>
<!--[if IE 9]>         <html class="no-js lt-ie10" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
    	{% include "./shared/head.html" %}
    	<title>MagNews | {% block title %}{% endblock title %}</title>
    </head>
    <body>
        <div id="page-wrapper">

            <div class="preloader themed-background">
                <h1 class="push-top-bottom text-light text-center"><strong>Pro</strong>UI</h1>
                <div class="inner">
                    <h3 class="text-light visible-lt-ie10"><strong>Loading..</strong></h3>
                    <div class="preloader-spinner hidden-lt-ie10"></div>
                </div>
            </div>

            <div id="page-container" class="sidebar-partial sidebar-visible-lg sidebar-no-animations">

                <!-- Main Sidebar -->
                {% include "./shared/sidebar.html" %}
                <!-- END Main Sidebar -->

                <!-- Main Container -->
                {% block content %}
                    
                {% endblock content %}
                <!-- END Main Container -->
            
            </div>
            <!-- END Page Container -->
        </div>
        <!-- END Page Wrapper -->

        <!-- Scroll to top link, initialized in js/app.js - scrollToTop() -->
        <a href="#" id="to-top"><i class="fa fa-angle-double-up"></i></a>

        <!-- END User Settings -->


        {% block scripts_table %}
        {% endblock scripts_table %}

        {% block scripts %}
        {% endblock scripts %}
 


    </body>
</html>

templates/dashboard/dashboard.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}{{block.super}} Home{% endblock title %}

{% block content %}

<div id="main-container">
	
	<!-- Header -->    
	{% include "./shared/header.html" %}
    <!-- END Header -->

    <!-- Page content -->
    <div id="page-content">

        <!-- Mini Top Stats Row -->
        <div class="row">
            <div class="col-sm-6 col-lg-3">
                <!-- Widget -->
                <a href="page_ready_article.html" class="widget widget-hover-effect1">
                    <div class="widget-simple">
                        <div class="widget-icon pull-left themed-background-autumn animation-fadeIn">
                            <i class="fa fa-file-text"></i>
                        </div>
                        <h3 class="widget-content text-right animation-pullDown">
                            New <strong>Article</strong><br>
                            <small>Mountain Trip</small>
                        </h3>
                    </div>
                </a>
                <!-- END Widget -->
            </div>
            <div class="col-sm-6 col-lg-3">
                <!-- Widget -->
                <a href="page_comp_charts.html" class="widget widget-hover-effect1">
                    <div class="widget-simple">
                        <div class="widget-icon pull-left themed-background-spring animation-fadeIn">
                            <i class="gi gi-usd"></i>
                        </div>
                        <h3 class="widget-content text-right animation-pullDown">
                            + <strong>250%</strong><br>
                            <small>Sales Today</small>
                        </h3>
                    </div>
                </a>
                <!-- END Widget -->
            </div>
            <div class="col-sm-6 col-lg-3">
                <!-- Widget -->
                <a href="page_ready_inbox.html" class="widget widget-hover-effect1">
                    <div class="widget-simple">
                        <div class="widget-icon pull-left themed-background-fire animation-fadeIn">
                            <i class="gi gi-envelope"></i>
                        </div>
                        <h3 class="widget-content text-right animation-pullDown">
                            5 <strong>Messages</strong>
                            <small>Support Center</small>
                        </h3>
                    </div>
                </a>
                <!-- END Widget -->
            </div>
            <div class="col-sm-6 col-lg-3">
                <!-- Widget -->
                <a href="page_comp_gallery.html" class="widget widget-hover-effect1">
                    <div class="widget-simple">
                        <div class="widget-icon pull-left themed-background-amethyst animation-fadeIn">
                            <i class="gi gi-picture"></i>
                        </div>
                        <h3 class="widget-content text-right animation-pullDown">
                            +30 <strong>Photos</strong>
                            <small>Gallery</small>
                        </h3>
                    </div>
                </a>
                <!-- END Widget -->
            </div>
        </div>
        <!-- END Mini Top Stats Row -->

    </div>
    <!-- END Page Content -->

    <!-- Footer -->
    <footer class="clearfix">
        <div class="pull-right">
            Crafted with <i class="fa fa-heart text-danger"></i> by <a href="http://goo.gl/vNS3I" target="_blank">pixelcave</a>
        </div>
        <div class="pull-left">
            <span id="year-copy"></span> &copy; <a href="http://goo.gl/TDOSuC" target="_blank">ProUI 3.8</a>
        </div>
    </footer>
    <!-- END Footer -->
</div>

{% endblock content %}

{% block scripts %}
	{% include "./shared/scripts.html" %}
{% endblock scripts %}

templates/dashboard/news_add.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}{{block.super}} Home{% endblock title %}

{% block content %}>

<!-- Main Container -->
<div id="main-container">

	<!-- Header -->    
	{% include "./shared/header.html" %}
    <!-- END Header -->

    <!-- Page content -->
    <div id="page-content">
        <!-- Datatables Header -->
        <div class="content-header">
            <div class="header-section">
                <h1>
                    <i class="fa fa-table"></i>Add news<br><small>You can Add, Edit and Delete your data!</small>
                </h1>
            </div>
        </div>
        <ul class="breadcrumb breadcrumb-top">
            <li>News</li>
            <li><a href="/panel/news/add">Add</a></li>
        </ul>
        <!-- END Datatables Header -->

        <!-- Datatables Content -->
        <div class="block full">
            <div class="block-title">
                <h2><strong>Add</strong> News</h2>
            </div>

            <div class="table-responsive">
                
            </div>
        </div>
        <!-- END Datatables Content -->
    </div>
    <!-- END Page Content -->

    <!-- Footer -->
    {% include "./shared/footer.html" %}
    <!-- END Footer -->
</div>

{% endblock content %}

{% block scripts_table %}
	{% include "./shared/scripts_table.html" %}
{% endblock scripts_table %}

templates/dashboard/shared/footer.html
{% load static %}

    <footer class="clearfix">
        <div class="pull-right">
            Crafted with <i class="fa fa-heart text-danger"></i> by <a href="http://goo.gl/vNS3I" target="_blank">pixelcave</a>
        </div>
        <div class="" style="text-align:center;">
            Develoved with <i class="fa fa-heart text-danger"></i> by <a href="" target="_blank">ING AFTER 60</a> &copy; 2021, August 17
        </div>
    </footer>

templates/dashboard/shared/head.html
{% load static %}

        <meta charset="utf-8">

        <meta name="description" content="ProUI is a Responsive Bootstrap Admin Template created by pixelcave and published on Themeforest.">
        <meta name="author" content="pixelcave">
        <meta name="robots" content="noindex, nofollow">
        <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0">

        <!-- Icons -->
        <!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
        <link rel="shortcut icon" href="{% static 'dashboard/img/favicon.png' %}">
        <link rel="apple-touch-icon" href="{% static 'dashboard/img/icon57.png' %}" sizes="57x57">
        <link rel="apple-touch-icon" href="{% static 'dashboard/img/icon72.png' %}" sizes="72x72">
        <link rel="apple-touch-icon" href="{% static 'dashboard/img/icon76.png' %}" sizes="76x76">
        <link rel="apple-touch-icon" href="{% static 'dashboard/img/icon114.png' %}" sizes="114x114">
        <link rel="apple-touch-icon" href="{% static 'dashboard/img/icon120.png' %}" sizes="120x120">
        <link rel="apple-touch-icon" href="{% static 'dashboard/img/icon144.png' %}" sizes="144x144">
        <link rel="apple-touch-icon" href="{% static 'dashboard/img/icon152.png' %}" sizes="152x152">
        <link rel="apple-touch-icon" href="{% static 'dashboard/img/icon180.png' %}" sizes="180x180">
        <!-- END Icons -->

        <!-- Stylesheets -->
        <!-- Bootstrap is included in its original form, unaltered -->
        <link rel="stylesheet" href="{% static 'dashboard/css/bootstrap.min.css' %}">

        <!-- Related styles of various icon packs and plugins -->
        <link rel="stylesheet" href="{% static 'dashboard/css/plugins.css' %}">

        <!-- The main stylesheet of this template. All Bootstrap overwrites are defined in here -->
        <link rel="stylesheet" href="{% static 'dashboard/css/main.css' %}">

        <!-- Include a specific file here from css/themes/ folder to alter the default theme of the template -->

        <!-- The themes stylesheet of this template (for using specific theme color in individual elements - must included last) -->
        <link rel="stylesheet" href="{% static 'dashboard/css/themes.css' %}">
        <!-- END Stylesheets -->

        <!-- Modernizr (browser feature detection library) -->
        <script src="{% static 'dashboard/js/vendor/modernizr.min.js' %}"></script>

templates/dashboard/shared/sidebar.html
{% load static %}

<div id="sidebar">
    <!-- Wrapper for scrolling functionality -->
    <div id="sidebar-scroll">
        <!-- Sidebar Content -->
        <div class="sidebar-content">
            <!-- Brand -->
            <a href="index.html" class="sidebar-brand">
                <i class="gi gi-flash"></i><span class="sidebar-nav-mini-hide"><strong>Pro</strong>UI</span>
            </a>
            <!-- END Brand -->

            <!-- User Info -->
            <div class="sidebar-section sidebar-user clearfix sidebar-nav-mini-hide">
                <div class="sidebar-user-avatar">
                    <a href="page_ready_user_profile.html">
                        <img src="{% static 'dashboard/img/placeholders/avatars/avatar2.jpg' %}" alt="avatar">
                    </a>
                </div>
                <div class="sidebar-user-name">John Doe</div>
                <div class="sidebar-user-links">
                    <a href="page_ready_user_profile.html" data-toggle="tooltip" data-placement="bottom" title="Profile"><i class="gi gi-user"></i></a>
                    <a href="page_ready_inbox.html" data-toggle="tooltip" data-placement="bottom" title="Messages"><i class="gi gi-envelope"></i></a>
                    <!-- Opens the user settings modal that can be found at the bottom of each page (page_footer.html in PHP version) -->
                    <a href="javascript:void(0)" class="enable-tooltip" data-placement="bottom" title="Settings" onclick="$('#modal-user-settings').modal('show');"><i class="gi gi-cogwheel"></i></a>
                    <a href="login.html" data-toggle="tooltip" data-placement="bottom" title="Logout"><i class="gi gi-exit"></i></a>
                </div>
            </div>
            <!-- END User Info -->

            <!-- Sidebar Navigation -->
            <ul class="sidebar-nav">
                <li>
                    <a href="index.html" class=" active"><i class="gi gi-stopwatch sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Dashboard</span></a>
                </li>
                <li>
                    <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="gi gi-shopping_cart sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">News</span></a>
                    <ul>
                        <li>
                            <a href="{% url 'dashboard:news_add' %}">Add news</a>
                        </li>
                        <li>
                            <a href="{% url 'dashboard:news_list' %}">News list</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- END Sidebar Navigation -->
        </div>
        <!-- END Sidebar Content -->
    </div>
    <!-- END Wrapper for scrolling functionality -->
</div>

templates/shared/header_logo_desktop.html
{% load static %}

<div class="wrap-logo container">
	<!-- Logo desktop -->		
	<div class="logo">
		<a href="{% url 'main:home_page' %}"><img src="{% static 'images/icons/logo-01.png' %}" alt="LOGO"></a>
	</div>	

	<!-- Banner -->
	<div class="banner-header">
		<a href="#"><img src="{% static 'images/banner-01.jpg' %}" alt="IMG"></a>
	</div>
</div>	

templates/shared/header_logo_mobile.html
{% load static %}

<div class="wrap-header-mobile">
	<!-- Logo moblie -->		
	<div class="logo-mobile">
		<a href="{% url 'main:home_page' %}"><img src="{% static 'images/icons/logo-01.png' %}" alt="IMG-LOGO"></a>
	</div>

	<!-- Button show menu -->
	<div class="btn-show-menu-mobile hamburger hamburger--squeeze m-r--8">
		<span class="hamburger-box">
			<span class="hamburger-inner"></span>
		</span>
	</div>
</div>

templates/shared/header_mobile_menu.html
{% load static %}

<div class="menu-mobile">
	<ul class="topbar-mobile">
		<li class="left-topbar">
			<span class="left-topbar-item flex-wr-s-c">
				<span>
					New York, NY
				</span>

				<img class="m-b-1 m-rl-8" src="{% static 'images/icons/icon-night.png' %}" alt="IMG">

				<span>
					HI 58° LO 56°
				</span>
			</span>
		</li>

		<li class="left-topbar">
			<a href="{% url 'about:about_page' %}" class="left-topbar-item">
				About
			</a>

			<a href="{% url 'contact:contact_page' %}" class="left-topbar-item">
				Contact
			</a>

			<a href="#" class="left-topbar-item">
				Sing up
			</a>

			<a href="#" class="left-topbar-item">
				Log in
			</a>
		</li>

		<li class="right-topbar">
			<a href="#">
				<span class="fab fa-facebook-f"></span>
			</a>

			<a href="#">
				<span class="fab fa-twitter"></span>
			</a>

			<a href="#">
				<span class="fab fa-pinterest-p"></span>
			</a>

			<a href="#">
				<span class="fab fa-vimeo-v"></span>
			</a>

			<a href="#">
				<span class="fab fa-youtube"></span>
			</a>
		</li>
	</ul>

	<ul class="main-menu-m">
		<li>
			<a href="index.html">Home</a>
			<ul class="sub-menu-m">
				<li><a href="index.html">Homepage v1</a></li>
				<li><a href="home-02.html">Homepage v2</a></li>
				<li><a href="home-03.html">Homepage v3</a></li>
			</ul>

			<span class="arrow-main-menu-m">
				<i class="fa fa-angle-right" aria-hidden="true"></i>
			</span>
		</li>

		<li>
			<a href="category-01.html">News</a>
		</li>

		<li>
			<a href="category-02.html">Entertainment </a>
		</li>

		<li>
			<a href="category-01.html">Business</a>
		</li>

		<li>
			<a href="category-02.html">Travel</a>
		</li>

		<li>
			<a href="category-01.html">Life Style</a>
		</li>

		<li>
			<a href="category-02.html">Video</a>
		</li>

		<li>
			<a href="#">Features</a>
			<ul class="sub-menu-m">
				<li><a href="category-01.html">Category Page v1</a></li>
				<li><a href="category-02.html">Category Page v2</a></li>
				<li><a href="blog-grid.html">Blog Grid Sidebar</a></li>
				<li><a href="blog-list-01.html">Blog List Sidebar v1</a></li>
				<li><a href="blog-list-02.html">Blog List Sidebar v2</a></li>
				<li><a href="blog-detail-01.html">Blog Detail Sidebar</a></li>
				<li><a href="blog-detail-02.html">Blog Detail No Sidebar</a></li>
				<li><a href="about.html">About Us</a></li>
				<li><a href="contact.html">Contact Us</a></li>
			</ul>

			<span class="arrow-main-menu-m">
				<i class="fa fa-angle-right" aria-hidden="true"></i>
			</span>
		</li>
	</ul>
</div>

templates/shared/header_topbar.html
{% load static %}

<div class="topbar">
	<div class="content-topbar container h-100">
		<div class="left-topbar">
			<span class="left-topbar-item flex-wr-s-c">
				<span>
					New York, NY
				</span>

				<img class="m-b-1 m-rl-8" src="{% static 'images/icons/icon-night.png' %}" alt="IMG">

				<span>
					HI 58° LO 56°
				</span>
			</span>

			<a href="{% url 'about:about_page' %}" class="left-topbar-item">
				About
			</a>

			<a href="{% url 'contact:contact_page' %}" class="left-topbar-item">
				Contact
			</a>

			<a href="#" class="left-topbar-item">
				Sing up
			</a>

			<a href="#" class="left-topbar-item">
				Log in
			</a>

			<a href="{% url 'dashboard:dashboard' %}" class="left-topbar-item">
				Admin
			</a>
		</div>

		<div class="right-topbar">
			<a href="#">
				<span class="fab fa-facebook-f"></span>
			</a>

			<a href="#">
				<span class="fab fa-twitter"></span>
			</a>

			<a href="#">
				<span class="fab fa-pinterest-p"></span>
			</a>

			<a href="#">
				<span class="fab fa-vimeo-v"></span>
			</a>

			<a href="#">
				<span class="fab fa-youtube"></span>
			</a>
		</div>
	</div>
</div>